apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    nginx.org/server-snippets: |
          ssl_verify_client optional;
spec:
  rules:
  - host:
    http:
      paths:
      - path: /html1
        backend:
          serviceName: s1
          servicePort: 80
      - path: /html2
        backend:
          serviceName: s2
          servicePort: 80
