apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my.test.domain
    http:
      paths:
      - path: /html1
        backend:
          serviceName: s1
          servicePort: 80
      - path: /html2
        backend:
          serviceName: s2
          servicePort: 80
